version: '3.9'
services:
  java:
    build: ./docker/java
    container_name: java-app
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=-Xmx512m
    volumes:
      - ./server/src:/usr/src:cached
    restart: unless-stopped